### ISSUE TITLE
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused

### ISSUE THREAD

**Issue by Darkcast** [sakkiii/MultiAV2#3]
followed the quick start guide 
installed everythig except docker-machine 
didnt touch the config.cfg
when I ran it it run perfectly but the page display an error page 
![image](https://user-images.githubusercontent.com/1676655/151415629-0759ba6c-da84-4dfa-9252-696d66334a09.png)

┌──(kali㉿kali)-[~/Downloads/MultiAV2/multiav]
└─$ sudo python3 scripts/runserver.py
--execute command: whereis docker
--execute command: docker ps
--execute command: ls /tmp/malware
--execute command: mkdir /tmp/malware
Checking if all engines are pulled and pulling them if required...
All engines pulled!
Checking if all docker networks exist and creating them if required...
All networks ok!
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/web/application.py", line 280, in process
    return self.handle()
  File "/usr/local/lib/python3.9/dist-packages/web/application.py", line 271, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python3.9/dist-packages/web/application.py", line 517, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python3.9/dist-packages/web/application.py", line 495, in handle_class
    return tocall(*args)
  File "/home/kali/Downloads/MultiAV2/multiav/webapi.py", line 747, in GET
    with CDbSamples() as db:
  File "/home/kali/Downloads/MultiAV2/multiav/webapi.py", line 100, in __init__
    self.create_schema()
  File "/home/kali/Downloads/MultiAV2/multiav/webapi.py", line 110, in create_schema
    with self.db.transaction():
  File "/usr/local/lib/python3.9/dist-packages/web/db.py", line 1185, in transaction
    return Transaction(self.ctx)
  File "/usr/local/lib/python3.9/dist-packages/web/db.py", line 683, in _getctx
    self._load_context(self._ctx)
  File "/usr/local/lib/python3.9/dist-packages/web/db.py", line 695, in _load_context
    ctx.db = self._connect(self.keywords)
  File "/usr/local/lib/python3.9/dist-packages/web/db.py", line 1232, in _connect
    conn = DB._connect(self, keywords)
  File "/usr/local/lib/python3.9/dist-packages/web/db.py", line 723, in _connect
    return self.db_module.connect(**keywords)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?

**Comment by sakkiii** [comment]
You need to configure with correct database settings in config.cfg file, [database configuration details](https://github.com/sakkiii/MultiAV2/wiki/Configuration#database-settings)

**Comment by n33lix1337** [comment]
I have got the same Problem ... where do i need to setup database ? Do i need to set it up using docker ? Iam stuck at this ...

**Comment by sakkiii** [comment]
@n33lix1337 it's your choice how and where you setup your database but database should be reachable from multiav machine.
Also make sure database port is exposed if you are using containers.
